# SQLite.
# gem install sql2
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Acer@123456
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: blog-app

test:
  <<: *default
  database: blog-app

production:
  <<: *default
  database: blog-app
  username: root
  password: Acer@123456
